import pandas as pd
from typing import Dict

def carregar_dados(filepath: str = "chamados.csv") -> pd.DataFrame:
    """Load and preprocess the chamados data from CSV."""
    df = pd.read_csv(filepath, sep=";", encoding="utf-8")
    df["Data"] = pd.to_datetime(df["Data"], dayfirst=True, errors="coerce")
    df["Resolvido"] = pd.to_datetime(df["Resolvido"], dayfirst=True, errors="coerce")
    df["Chassi"] = df["Chassi"].fillna("").astype(str).str.strip().str.replace(".0", "", regex=False).replace("", "N/A")
    df["RTM"] = df["RTM"].apply(lambda x: "SIM" if "RTM" in str(x).upper() else "NÃO")
    return df

def carregar_dados_merged(
    filepath1: str = "chamados.csv",
    filepath2: str = "chamados_fechados.csv"
) -> pd.DataFrame:
    """Load, merge, and preprocess chamados and chamados_fechados data from CSVs."""
    df1 = pd.read_csv(filepath1, sep=";", encoding="utf-8")
    df2 = pd.read_csv(filepath2, sep=";", encoding="utf-8")
    df = pd.concat([df1, df2], ignore_index=True)
    # Ensure 'Data' and 'Resolvido' columns exist
    for col in ["Data", "Resolvido"]:
        if col not in df.columns:
            df[col] = pd.NA
    # Parse as datetime
    df["Data"] = pd.to_datetime(df["Data"], dayfirst=True, errors="coerce")
    df["Resolvido"] = pd.to_datetime(df["Resolvido"], dayfirst=True, errors="coerce")
    # Clean Chassi
    df["Chassi"] = df["Chassi"].fillna("").astype(str).str.strip().str.replace(".0", "", regex=False).replace("", "N/A")
    # RTM logic
    df["RTM"] = df["RTM"].apply(lambda x: "SIM" if "RTM" in str(x).upper() else "NÃO")
    # Deduplicate by 'SS' and 'Tarefa', keeping the most recent by 'Data'
    if all(col in df.columns for col in ["Data", "SS", "Tarefa"]):
        df = df.sort_values("Data", ascending=False).drop_duplicates(subset=["SS", "Tarefa"], keep="first")
    df = df.reset_index(drop=True)
    return df

# Dicionários de substituição (de_para)
de_para_proprietario: Dict[str, str] = {
    "Oliveira, Cassio Fonseca Farias de (Cassio)": "CÁSSIO OLIVEIRA",
    "Simões, Wanderley": "WANDERLEY SIMÕES",
    "Santos de Lima, Antônio Vinicius dos (Antônio Vinicius dos Santos de Lima)": "ANTÔNIO DOS SANTOS",
    "Nogueira, Victor M": "VICTOR NOGUEIRA",
    "QUIRINO, RICARDO": "RICARDO QUIRINO",
    "Ferreira De Araujo, Jose Roberto": "JOSÉ ROBERTO",
    "Lucas, Jefferson Monteiro da Silva": "JEFFERSON LUCAS",
    "Silva, Márcio (Contractor) (Márcio (Contractor) Silva)": "MÁRCIO SILVA",
    "Longo, Dante M (Dante M. Longo)": "DANTE LONGO",
    "dos Santos, Otacílio (Contractor) (Otacílio (Contractor) dos Santos)": "OTACÍLIO DOS SANTOS",
    "de Freitas, Fabio (Contractor) (Fabio (Contractor) de Freitas)": "FÁBIO DE FREITAS",
    "Araujo, Alessandro Fabiano De": "ALESSANDRO ARAUJO",
    "Calado, Marcos Aurelio Cavalcanti": "MARCOS CALADO",
    "BRAGA, PEDRO XAVIER": "PEDRO BRAGA",
    "Oliveira, Lucas F": "LUCAS OLIVEIRA",
    "SILVA, RAFAEL DOUGLAS DIAS DA": "RAFAEL SILVA",
    "SILVA, ROBERTO FERNANDES": "ROBERTO SILVA",
    "Silva, Rodrigo Jose Bussolaro": "RODRIGO SILVA",
    "Sobrinho, Luan B": "LUAN SOBRINHO",
}

de_para_mantenedor: Dict[str, str] = {
    "MACIEL, FONTES FRANJAKSON - NTEC INSTALACOES HIDRAULICAS LTDA.":"NTEC",
    "SALES, LUIZ - SOCIEDADE DE MANUTENCAO TECNICA SOMATEC LTDA":"SOMATEC",
    "HENRIQUE, THIAGO - CM2 COMERCIO E SERVICOS LTDA EPP":"CM2",
    "EVANDRO, - FLOTECK COMERCIO E SERVICOS ESPECIALIZADOS LTDA":"FLOTECK",
    "RIGOBERTO, FRANCISCO - F R RIBEIRO MECANICA SAO CRISTOVAO SERVICOS ELETRONICOS LTDA":"MEC. SÃO CRISTÓVÃO",
    "ESDRAS ARR, - E PASCOAL COM SERV E ASSIST TE":"PASCOAL",
    "SALES, - S L INSTALACAO P POSTOS DE SE":"SL INSTALAÇÃO",
    "NEVES, - TEKSUL MANUTENÇÃO DE BOMBAS PARA COMBUSTÍVEL EIRELI":"TEKSUL",
    "MOURA, ALEXSANDRE - ALEXSANDRE LIZ DE MOURA":"BOMBAGAS",
    "JESSICA, THAINA - THAINA JESSICA DA COSTA RODRIGUES":"PETROPOSTO",
    "SERGIO, - SERVTEC COMERCIO E SERVICO LTD":"SERVTEC",
    "SALES, LUIZ - TECNICA L S COMERCIAL E SERVI":"TECNICA LS",
    "PINTO, ANDREZA - C A INSTALACAO E MANUTENCAO EM POSTOS DE COMBUSTIVEIS LTDA":"C A INSTALAÇÃO",
    "LUCIANA, - ATENDE COMERCIO DE PECAS E CON":"ATENDE",
    "SILVA, REGINALD - SHEKINAH SHADDAI MANUTENCAO LTD":"SHEKINAH",
    "SRA.FERNAN, - FORTE INSTALACAO E MANUTENCAO":"FORTE",
    "FREITAS, LUCIANO - BHPUMP DO BRASIL LTDA":"BHPUMP",
    "SANTOS, VANDERLEY - VANDERLEY PEREIRA DOS SANTOS":"PETROLINK",
    "FAVERO, PAULA - CENTURY FLEX COMERCIO DE PECAS PARA BOMBAS DE COMBUSTIVEIS LTDA":"CENTURY",
    "ROCHA, ROBERTO - SIGNOS MRWG MANUTENCAO LTDA ME":"SIGNOS",
    "GONZAGA, MANOEL - LMG COMERCIO SERVICOS E MANUTENCAO LTDA":"LMG",
    "Mendes, Andre - M E A SILVA MENDES MANUTENCAO E REPARACAO ME":"MERIVA",
    "CAMPOS, SANDREIA - CONSTRUTORA CENTAURUS DO BRASIL LTDA":"CENTAURUS",
    "UNKNOWN, CASSIA - ARBTEK SOLUCOES INTEGRADAS LTDA":"ARBTEK",
    "COSTA, GUSTAVO - CONSERTEC BALANCAS E BOMBAS LTDA ME":"CONSERTEC",
    "JUNIOR, LUIZ ZORZI - ZORZITEC CONSULTORIA EIRELI ME":"ZORZITEC",
    "MENEZES SOARES, ALTEVIR - JUMPER SERVICOS TECNICOS DE BOMBAS DE COMBUSTIVEIS LTDA":"JUMPER",
    "DE MATTOS, PERI JACI - MULTITEC SOLUCOES EM POSTOS AUTOMOTIVOS LTDA":"MULTITEC",
    "., Romario - DINIZ ASSISTENCIA TECNICA LTDA":"DINIZ",
    "Serafim, Joao - JS DE SOUSA MANUTENCAO ME":"JS MANUTENÇÃO",
    "Silva, Rodrigo - EBENEZER COMECIO E MANUTENCAO":"EBENEZER",
    "Neto, Jorge - EWJ INSTALACAO E MANUTENCAO DE EQUIPAMENTOS PARA POSTOS DE COMBUSTIVEIS LTDA":"EWJ",
    "AMORIM DE OLIVE, LEONORA - L DE ALMEIDA FERREIRA LTDA":"NOVA ERA",
    "RAMOS, CARLOS - MECANICA DE BOMBAS RAMOS LTDA":"MEC. BOMBAS RAMOS",
    "COSTA, HELIO - REAL MANUTENCAO E INSTALACAO EM POSTOS E SERVICOS LTDA":"REAL MANUTENÇÃO",
    "ANTONIO, - A DE JESUS E SOUZA DOURADO LTD":"FUTURA",
    "RODRIGUES, RIVALDO - SMR MANUTENCAO E REPARACAO EIRELI ME":"SMR",
    "amaro, florisvaldo - SERVITEC - MANUTENCAO E INSTALACAO DE EQUIPAMENTOS EM POSTOS DE COMBUSTIVEIS LTDA":"SERVITEC",
    "SR. LAZARO, - LAZARO MARTINS SILVA SOUZA ME":"LÁZARO",
    "Belarmino, Marcos - SOS SYSTEM TECNOLOGIA EM INFORMATICA LTDA":"SOS SYSTEM",
    "DO MONTE, CARLOS JORGE - PERMANENTE MANUTENCAO DE MAQUINAS E EQUIPAMENTOS EIRELI":"PERMANENTE",
    "MENDES, - IMASEL LTDA":"IMASEL",
    "ANDRADE, JAIR - JMA PRESTADORA DE SERVICOS LTDA":"JMA",
    "ANDREZA, - UBERPOSTOS LOGISTICA E EQUIP":"UBERPOSTOS",
    "LUZENILDO, - DANTEC ASSITENCIA TECNICA LTDA":"DANTEC",
    "SANTANA, DORLAN - TECHPETRO SOLUCOES SERVICOS DE MANUTENCAO LTDA":"TECHPETRO",
    "Soares, Altevir - JUMPER MATERIAIS E SERVICOS PARA POSTOS DE COMBUSTIVEIS EIRELI ME":"JUMPER",
    "., RIBAMAR - CENTURY COM E ASSIST TECNICA EM POSTO DE COMBUSTIVEL LTDA":"CENTURY COM E ASSIST",
    "ALIPIO CRUZ, HELENO - H A CRUZ TECNOLOGIA LTDA":"H A CRUZ TECNOLOGIA",
    "CAMPOS, PATRÍCIA - PETROPOSTO COMERCIO E SERVICO LTDA":"PETROPOSTO",
    "DOS SANTOS, GIVONI NATASHA - ATLAS COMERCIO DE MATERIAL ELETRICO E SERVICOS DE INSTALACAO LTDA":"ATLAS COMERCIO",
    "DRESSER INDSTRI, - WAYNE BRASIL DRESSER IND E COM LTDA":"WAYNE BRASIL DRESSER",
    "FERREIRA, RONDINEL - RONDINEL FERREIRA DE SANTANA":"RONDINEL FERREIRA",
    "Fernandes, Alecio - Uberpostos Instalacoes em postos de combustiveis Ltda.":"UBERPOSTOS",
    "JAOA, - JI SOLUCOES LTD EPP":"JI SOLUCOES",
    "LACERDA, IVAN - SOFT POSTOS LTDA":"SOFT POSTOS",
    "LEONARDO, - UBERPOSTOS LOGISTICA E EQUIP": "UBERPOSTOS",
    "LUCAS/ANDR, - Uberpostos Instalacoes em postos de combustiveis Ltda":"UBERPOSTOS",
    "MORAES, BRUNO - MOTORVAC EQUIPAMENTOS HIDRAULICOS E MECANICOS LTDA":"MOTORVAC",
    "Moura, Jaimerson - J C MOURA ME":"J C MOURA",
    "Santos, Abraham - MANOEL GONZAGA DOS SANTOS":"MANOEL GONZAGA",
    "Silva, Rodrigo - TECNO PUMP COMERCIO DE PECAS PBOMBAS COMBUSTIVEL LTDA - ME":"TECNO PUMP",
    "Soares, Altevir - JUMPER MATERIAIS E SERVICOS PARA POSTOS DE COMBUSTIVEIS EIRELI ME":"JUMPER",
    "SALES, - UBERPOSTOS LOGISTICA E EQUIP": "UBERPOSTOS"
}

de_para_especialista: Dict[str, str] = {
    "PINTO, ANDREZA - C A INSTALACAO E MANUTENCAO EM POSTOS DE COMBUSTIVEIS LTDA":"LUCAS",
    "MACIEL, FONTES FRANJAKSON - NTEC INSTALACOES HIDRAULICAS LTDA.":"LUCIANO",
    "SALES, - S L INSTALACAO P POSTOS DE SE":"LUCAS",
    "SALES, LUIZ - TECNICA L S COMERCIAL E SERVI":"LUCAS",
    "GONZAGA, MANOEL - LMG COMERCIO SERVICOS E MANUTENCAO LTDA":"LUCIANO",
    "MOURA, ALEXSANDRE - ALEXSANDRE LIZ DE MOURA":"LUCAS",
    "NEVES, - TEKSUL MANUTENÇÃO DE BOMBAS PARA COMBUSTÍVEL EIRELI":"LUCAS",
    "Serafim, Joao - JS DE SOUSA MANUTENCAO ME":"LUCIANO",
    "RIGOBERTO, FRANCISCO - F R RIBEIRO MECANICA SAO CRISTOVAO SERVICOS ELETRONICOS LTDA":"LUCIANO",
    "ANDREZA, - UBERPOSTOS LOGISTICA E EQUIP":"LUCAS",
    "ANTONIO, - A DE JESUS E SOUZA DOURADO LTD":"LUCIANO",
    "SILVA, REGINALD - SHEKINAH SHADDAI MANUTENCAO LTD":"LUCIANO",
    "RAMOS, CARLOS - MECANICA DE BOMBAS RAMOS LTDA":"LUCAS",
    "amaro, florisvaldo - SERVITEC - MANUTENCAO E INSTALACAO DE EQUIPAMENTOS EM POSTOS DE COMBUSTIVEIS LTDA":"ALESSANDRO",
    "Mendes, Andre - M E A SILVA MENDES MANUTENCAO E REPARACAO ME":"LUCAS",
    "SALES, - UBERPOSTOS LOGISTICA E EQUIP":"ALESSANDRO",
    "LUCIANA, - ATENDE COMERCIO DE PECAS E CON":"LUCIANO",
    "AMORIM DE OLIVE, LEONORA - L DE ALMEIDA FERREIRA LTDA":"LUCIANO",
    "HENRIQUE, THIAGO - CM2 COMERCIO E SERVICOS LTDA EPP":"LUCAS",
    "SRA.FERNAN, - FORTE INSTALACAO E MANUTENCAO":"LUCIANO",
    "JESSICA, THAINA - THAINA JESSICA DA COSTA RODRIGUES":"LUCIANO",
    "FREITAS, LUCIANO - BHPUMP DO BRASIL LTDA":"ALESSANDRO",
    "SANTOS, VANDERLEY - VANDERLEY PEREIRA DOS SANTOS":"ALESSANDRO",
    "Silva, Rodrigo - EBENEZER COMECIO E MANUTENCAO":"LUCAS",
    "SERGIO, - SERVTEC COMERCIO E SERVICO LTD":"LUCIANO",
    "., Romario - DINIZ ASSISTENCIA TECNICA LTDA":"LUCAS",
    "UNKNOWN, CASSIA - ARBTEK SOLUCOES INTEGRADAS LTDA":"LUCAS",
    "SALES, LUIZ - SOCIEDADE DE MANUTENCAO TECNICA SOMATEC LTDA":"ALESSANDRO",
    "RODRIGUES, RIVALDO - SMR MANUTENCAO E REPARACAO EIRELI ME":"LUCIANO",
    "MENDES, - IMASEL LTDA":"LUCIANO",
    "ESDRAS ARR, - E PASCOAL COM SERV E ASSIST TE":"LUCIANO",
    "ROCHA, ROBERTO - SIGNOS MRWG MANUTENCAO LTDA ME":"ALESSANDRO",
    "DE MATTOS, PERI JACI - MULTITEC SOLUCOES EM POSTOS AUTOMOTIVOS LTDA":"LUCAS",
    "COSTA, GUSTAVO - CONSERTEC BALANCAS E BOMBAS LTDA ME":"ALESSANDRO",
    "SR. LAZARO, - LAZARO MARTINS SILVA SOUZA ME":"LUCAS",
    "COSTA, HELIO - REAL MANUTENCAO E INSTALACAO EM POSTOS E SERVICOS LTDA":"LUCIANO",
    "Neto, Jorge - EWJ INSTALACAO E MANUTENCAO DE EQUIPAMENTOS PARA POSTOS DE COMBUSTIVEIS LTDA":"LUCIANO",
    "CAMPOS, SANDREIA - CONSTRUTORA CENTAURUS DO BRASIL LTDA":"LUCIANO",
    "JUNIOR, LUIZ ZORZI - ZORZITEC CONSULTORIA EIRELI ME":"LUCAS",
    "MENEZES SOARES, ALTEVIR - JUMPER SERVICOS TECNICOS DE BOMBAS DE COMBUSTIVEIS LTDA":"LUCIANO",
    "DO MONTE, CARLOS JORGE - PERMANENTE MANUTENCAO DE MAQUINAS E EQUIPAMENTOS EIRELI":"LUCIANO",
    "ANDRADE, JAIR - JMA PRESTADORA DE SERVICOS LTDA":"LUCAS",
    "Belarmino, Marcos - SOS SYSTEM TECNOLOGIA EM INFORMATICA LTDA":"LUCAS",
    "EVANDRO, - FLOTECK COMERCIO E SERVICOS ESPECIALIZADOS LTDA":"LUCAS",
    "FAVERO, PAULA - CENTURY FLEX COMERCIO DE PECAS PARA BOMBAS DE COMBUSTIVEIS LTDA":"LUCAS",
    "LUZENILDO, - DANTEC ASSITENCIA TECNICA LTDA":"LUCIANO",
    "SANTANA, DORLAN - TECHPETRO SOLUCOES SERVICOS DE MANUTENCAO LTDA":"LUCIANO",
   "Soares, Altevir - JUMPER MATERIAIS E SERVICOS PARA POSTOS DE COMBUSTIVEIS EIRELI ME":"LUCIANO",
    "., RIBAMAR - CENTURY COM E ASSIST TECNICA EM POSTO DE COMBUSTIVEL LTDA":"TBD",
    "ALIPIO CRUZ, HELENO - H A CRUZ TECNOLOGIA LTDA":"TBD",
    "CAMPOS, PATRÍCIA - PETROPOSTO COMERCIO E SERVICO LTDA":"TBD",
    "DOS SANTOS, GIVONI NATASHA - ATLAS COMERCIO DE MATERIAL ELETRICO E SERVICOS DE INSTALACAO LTDA":"TBD",
    "DRESSER INDSTRI, - WAYNE BRASIL DRESSER IND E COM LTDA":"TBD",
    "FERREIRA, RONDINEL - RONDINEL FERREIRA DE SANTANA":"TBD",
    "Fernandes, Alecio - Uberpostos Instalacoes em postos de combustiveis Ltda.":"TBD",
    "JAOA, - JI SOLUCOES LTD EPP":"TBD",
    "LACERDA, IVAN - SOFT POSTOS LTDA":"TBD",
    "LEONARDO, - UBERPOSTOS LOGISTICA E EQUIP": "LUCAS",
    "LUCAS/ANDR, - Uberpostos Instalacoes em postos de combustiveis Ltda":"LUCAS",
    "MORAES, BRUNO - MOTORVAC EQUIPAMENTOS HIDRAULICOS E MECANICOS LTDA":"TBD",
    "Moura, Jaimerson - J C MOURA ME":"TBD",
    "Santos, Abraham - MANOEL GONZAGA DOS SANTOS":"TBD",
    "Silva, Rodrigo - TECNO PUMP COMERCIO DE PECAS PBOMBAS COMBUSTIVEL LTDA - ME":"TBD",
    "Soares, Altevir - JUMPER MATERIAIS E SERVICOS PARA POSTOS DE COMBUSTIVEIS EIRELI ME":"LUCIANO",
    "SALES, - UBERPOSTOS LOGISTICA E EQUIP":"LUCAS"
}